### ISSUE TITLE
10월 23일 피드백, TODO

### ISSUE THREAD

**Issue by YeonSeong-Lee** [42OpenGL/opengl_wrapper#7]
## TODO
- [x] buffer class에서 inline으로 초기화해주는게 더 좋을 듯
- [ ] buffer가 여러개일 때 대응
- [ ] vertices가 여러개일 때 대응
- [x] 동적할당때 초기화해주고, 동적해제 가드를 통해, 안전하게 해제하기
- [x] buffer class, setVertices()함수에서 레퍼런스로 받아서 더 효율적으로 하기(또는 swap으로 더 효율적으로 하기)
- [x] ShaderProgram에서 shader 확장가능성 고려하기
- [x] Window 클래스에서 창크기와 창이름도 설정할 수 있게 해주기

## 관련 커밋
https://github.com/42OpenGL/opengl_wrapper/commit/f1aa01a90a129163b49d13db92ef7893588108e4
